[package]
name = "snakef2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.21.0"
rand = "0.8.5"
itertools = "0.12.0"
